version: "2"

volumes:
  vol_rabbitmq:

services:
  robot-cleaner:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    ports:
      - 5000:5000
  postgres:
    build:
      context: ../
      dockerfile: ./docker/DockerfileDB
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=example
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
